# Generated by Django 5.0.4 on 2024-05-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expiration_month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expiration_year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
    ]
