# Generated by Django 5.0.4 on 2024-04-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
