# Generated by Django 5.0.4 on 2024-04-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
