# Generated by Django 5.0.4 on 2024-05-01 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_login_login_alter_login_title_alter_login_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
